# Generated by Django 3.1.6 on 2022-04-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0003_auto_20220417_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertState', models.CharField(choices=[('CANCELLED', ' cancelled'), ('ACTIVE', 'active')], default='ACTIVE', max_length=20)),
                ('acceptedState', models.CharField(choices=[('NOTYET', 'not yet '), ('Accepted', 'accepted')], default='NOTYET', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
