# Generated by Django 3.1.6 on 2022-04-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0005_auto_20220417_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acceptedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='greenev.association'),
        ),
        migrations.AddField(
            model_name='alert',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='alert',
            name='commune',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='discription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='ville',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='wilaya',
            field=models.CharField(default='', max_length=50),
        ),
    ]
