# Generated by Django 3.1.6 on 2022-04-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0007_auto_20220417_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
