# Generated by Django 3.1.6 on 2022-04-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0010_evenement_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='address',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='wilaya',
        ),
    ]
