# Generated by Django 3.1.6 on 2022-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0011_auto_20220418_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='alert',
            name='acceptedState',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alertState',
            field=models.BooleanField(default=True),
        ),
    ]
