# Generated by Django 3.1.6 on 2022-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0012_auto_20220418_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
