# Generated by Django 4.0.1 on 2022-04-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0013_auto_20220418_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementnotif',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='evenementnotif',
            name='notification_ptr',
        ),
        migrations.RemoveField(
            model_name='review',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
        migrations.DeleteModel(
            name='Evenementnotif',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
