# Generated by Django 4.0.1 on 2022-04-19 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0014_remove_evenementnotif_evenement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EvenementState', models.CharField(choices=[('DISPO', 'disponile '), ('NOTDISPO', 'not disponible '), ('INPROGRESS', ' in progress '), ('REPORTED', 'reported ')], default='DISPO', max_length=20)),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('dateUpdate', models.DateField(blank=True, null=True)),
                ('dateEnd', models.DateField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, default='/placeholder1.png', null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, default='/placeholder2.png', null=True, upload_to='')),
                ('alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='greenev.alert')),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='greenev.association')),
                ('members', models.ManyToManyField(to='greenev.Citoyen')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greenev.evenement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='greenev.citoyen')),
            ],
        ),
    ]
