# Generated by Django 4.0.1 on 2022-04-19 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0015_evenement_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenementnotif',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='greenev.notification')),
                ('evenement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='greenev.evenement')),
            ],
            bases=('greenev.notification',),
        ),
    ]
