# Generated by Django 3.1.6 on 2022-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0016_evenementnotif'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='reson',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='EvenementState',
            field=models.CharField(choices=[('DISPO', 'disponile '), ('NOTDISPO', 'not disponible '), ('INPROGRESS', ' in progress '), ('REPORTED', 'reported '), ('CANCELLED', 'cancelled ')], default='DISPO', max_length=20),
        ),
    ]
