# Generated by Django 3.1.6 on 2022-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0017_auto_20220419_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='EvenementState',
            field=models.CharField(choices=[('DISPO', 'disponile '), ('NOTDISPO', 'not disponible '), ('INPROGRESS', ' in progress '), ('REPORTED', 'reported '), ('CANCELLED', 'cancelled '), ('FINISHED', 'finishef ')], default='DISPO', max_length=20),
        ),
    ]
