# Generated by Django 4.0.1 on 2022-04-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0018_auto_20220419_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
