# Generated by Django 4.0.1 on 2022-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenev', '0019_remove_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
